#!/usr/bin/env bash
#
# Suijin one-command installer (macOS / Linux)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/0xwi11iam/Suijin/main/install.sh | bash
#
# Installs Suijin into $SUIJIN_INSTALL_DIR (default ~/.suijin), creates an
# isolated virtualenv, and drops a `suijin` command on your PATH. Then verify:
#
#   suijin doctor     # check the environment
#   suijin            # launch the interface
#
# Environment overrides:
#   SUIJIN_INSTALL_DIR   where to install (default $HOME/.suijin)
#   SUIJIN_BIN_DIR       where to put the `suijin` launcher (default $HOME/.local/bin)
#   SUIJIN_REPO          source repo (default the GitHub URL; may be a local path)
#   SUIJIN_NO_PATH_EDIT  set to 1 to skip editing shell rc files
#
set -euo pipefail

# Medusa-era env overrides still honored (rename compatibility)
REPO_URL="${SUIJIN_REPO:-${MEDUSA_REPO:-https://github.com/0xwi11iam/Suijin.git}}"
INSTALL_DIR="${SUIJIN_INSTALL_DIR:-${MEDUSA_INSTALL_DIR:-$HOME/.suijin}}"
BIN_DIR="${SUIJIN_BIN_DIR:-${MEDUSA_BIN_DIR:-$HOME/.local/bin}}"
export SUIJIN_NO_PATH_EDIT="${SUIJIN_NO_PATH_EDIT:-${MEDUSA_NO_PATH_EDIT:-0}}"

# Migrate a Medusa-era installation directory when Suijin's doesn't exist
if [ ! -d "$INSTALL_DIR" ] && [ -d "$HOME/.medusa" ]; then
  info "Migrating legacy ~/.medusa -> $INSTALL_DIR"
  mv "$HOME/.medusa" "$INSTALL_DIR"
fi

info()  { printf "\033[32m[suijin]\033[0m %s\n" "$*"; }
warn()  { printf "\033[33m[suijin]\033[0m %s\n" "$*"; }
error() { printf "\033[31m[suijin]\033[0m %s\n" "$*"; exit 1; }

# ── Platform ────────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Darwin|Linux) ;;
  *) error "Unsupported OS: $OS (macOS and Linux only)";;
esac

# ── Prerequisites ───────────────────────────────────────────────────────
for dep in git python3; do
  command -v "$dep" >/dev/null 2>&1 || error "$dep is required but not found."
done

# ── Fetch the source ────────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
REPO_DIR="$INSTALL_DIR/repo"

if [ -d "$REPO_URL/.git" ]; then
  info "Copying local source: $REPO_URL"
  rm -rf "$REPO_DIR"
  cp -R "$REPO_URL" "$REPO_DIR"
elif [ -d "$REPO_DIR/.git" ]; then
  info "Updating existing checkout"
  git -C "$REPO_DIR" pull --ff-only
else
  info "Cloning $REPO_URL"
  git clone --depth 1 "$REPO_URL" "$REPO_DIR"
fi

# ── Agent workspace layout ──────────────────────────────────────────────
# Canonical workspace is <repo>/suijin_agent/; suijin/suijin_agent is a
# symlink -> ../suijin_agent. Merge any legacy real dir up, then link.
mkdir -p "$REPO_DIR/suijin_agent"
if [ -d "$REPO_DIR/suijin/suijin_agent" ] && [ ! -L "$REPO_DIR/suijin/suijin_agent" ]; then
  cp -R "$REPO_DIR/suijin/suijin_agent/." "$REPO_DIR/suijin_agent/" 2>/dev/null || true
  rm -rf "$REPO_DIR/suijin/suijin_agent"
fi
ln -sfn ../suijin_agent "$REPO_DIR/suijin/suijin_agent"

# ── Virtualenv + dependencies ───────────────────────────────────────────
VENV="$INSTALL_DIR/venv"
if [ ! -x "$VENV/bin/python" ]; then
  info "Creating virtualenv at $VENV"
  python3 -m venv "$VENV"
fi
info "Installing Python dependencies"
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -r "$REPO_DIR/suijin/requirements.txt"

# ── `suijin` launcher ───────────────────────────────────────────────────
mkdir -p "$BIN_DIR"
LAUNCHER="$BIN_DIR/suijin"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Suijin launcher — generated by install.sh
exec "$VENV/bin/python" "$REPO_DIR/suijin/cli.py" "\$@"
EOF
chmod +x "$LAUNCHER"
info "Installed launcher: $LAUNCHER"

# ── PATH ────────────────────────────────────────────────────────────────
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  if [ "${SUIJIN_NO_PATH_EDIT:-0}" = "1" ]; then
    warn "Add $BIN_DIR to your PATH, then run 'suijin'."
  else
    for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
      if [ -f "$rc" ] && ! grep -q "suijin PATH" "$rc" 2>/dev/null; then
        printf '\n# suijin PATH\nexport PATH="%s:$PATH"\n' "$BIN_DIR" >> "$rc"
        info "Updated $rc"
      fi
    done
    export PATH="$BIN_DIR:$PATH"
  fi
fi

# ── Verify ──────────────────────────────────────────────────────────────
info "Install complete."
"$VENV/bin/python" "$REPO_DIR/suijin/cli.py" doctor || true
echo
info "Start with:  suijin"
info "Verify with: suijin doctor"
