#!/usr/bin/env bash
#
# Medusa one-command installer (macOS / Linux)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/0xwi11iam/Medusa/main/install.sh | bash
#
# Installs Medusa into $MEDUSA_INSTALL_DIR (default ~/.medusa), creates an
# isolated virtualenv, and drops a `medusa` command on your PATH. Then verify:
#
#   medusa doctor     # check the environment
#   medusa            # launch the interface
#
# Environment overrides:
#   MEDUSA_INSTALL_DIR   where to install (default $HOME/.medusa)
#   MEDUSA_BIN_DIR       where to put the `medusa` launcher (default $HOME/.local/bin)
#   MEDUSA_REPO          source repo (default the GitHub URL; may be a local path)
#   MEDUSA_NO_PATH_EDIT  set to 1 to skip editing shell rc files
#
set -euo pipefail

REPO_URL="${MEDUSA_REPO:-https://github.com/0xwi11iam/Medusa.git}"
INSTALL_DIR="${MEDUSA_INSTALL_DIR:-$HOME/.medusa}"
BIN_DIR="${MEDUSA_BIN_DIR:-$HOME/.local/bin}"

info()  { printf "\033[32m[medusa]\033[0m %s\n" "$*"; }
warn()  { printf "\033[33m[medusa]\033[0m %s\n" "$*"; }
error() { printf "\033[31m[medusa]\033[0m %s\n" "$*"; exit 1; }

# ── Platform ────────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Darwin|Linux) ;;
  *) error "Unsupported OS: $OS (macOS and Linux only)";;
esac

# ── Prerequisites ───────────────────────────────────────────────────────
for dep in git python3; do
  command -v "$dep" >/dev/null 2>&1 || error "$dep is required but not found."
done

# ── Fetch the source ────────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
REPO_DIR="$INSTALL_DIR/repo"

if [ -d "$REPO_URL/.git" ]; then
  info "Copying local source: $REPO_URL"
  rm -rf "$REPO_DIR"
  cp -R "$REPO_URL" "$REPO_DIR"
elif [ -d "$REPO_DIR/.git" ]; then
  info "Updating existing checkout"
  git -C "$REPO_DIR" pull --ff-only
else
  info "Cloning $REPO_URL"
  git clone --depth 1 "$REPO_URL" "$REPO_DIR"
fi

# ── Agent workspace layout ──────────────────────────────────────────────
# Canonical workspace is <repo>/medusa_agent/; medusa/medusa_agent is a
# symlink -> ../medusa_agent. Merge any legacy real dir up, then link.
mkdir -p "$REPO_DIR/medusa_agent"
if [ -d "$REPO_DIR/medusa/medusa_agent" ] && [ ! -L "$REPO_DIR/medusa/medusa_agent" ]; then
  cp -R "$REPO_DIR/medusa/medusa_agent/." "$REPO_DIR/medusa_agent/" 2>/dev/null || true
  rm -rf "$REPO_DIR/medusa/medusa_agent"
fi
ln -sfn ../medusa_agent "$REPO_DIR/medusa/medusa_agent"

# ── Virtualenv + dependencies ───────────────────────────────────────────
VENV="$INSTALL_DIR/venv"
if [ ! -x "$VENV/bin/python" ]; then
  info "Creating virtualenv at $VENV"
  python3 -m venv "$VENV"
fi
info "Installing Python dependencies"
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -r "$REPO_DIR/medusa/requirements.txt"

# ── `medusa` launcher ───────────────────────────────────────────────────
mkdir -p "$BIN_DIR"
LAUNCHER="$BIN_DIR/medusa"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Medusa launcher — generated by install.sh
exec "$VENV/bin/python" "$REPO_DIR/medusa/cli.py" "\$@"
EOF
chmod +x "$LAUNCHER"
info "Installed launcher: $LAUNCHER"

# ── PATH ────────────────────────────────────────────────────────────────
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  if [ "${MEDUSA_NO_PATH_EDIT:-0}" = "1" ]; then
    warn "Add $BIN_DIR to your PATH, then run 'medusa'."
  else
    for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
      if [ -f "$rc" ] && ! grep -q "medusa PATH" "$rc" 2>/dev/null; then
        printf '\n# medusa PATH\nexport PATH="%s:$PATH"\n' "$BIN_DIR" >> "$rc"
        info "Updated $rc"
      fi
    done
    export PATH="$BIN_DIR:$PATH"
  fi
fi

# ── Verify ──────────────────────────────────────────────────────────────
info "Install complete."
"$VENV/bin/python" "$REPO_DIR/medusa/cli.py" doctor || true
echo
info "Start with:  medusa"
info "Verify with: medusa doctor"
